language: go
sudo: required
go:
  - 1.13
env:
  - CLICKHOUSE_VERSION=1.1.54390
  - CLICKHOUSE_VERSION=19.15.3.6
services:
  - docker
script: >-
  # Building executable file
  CGO_ENABLED=0 go build -ldflags "-w -s -X main.version=${TRAVIS_TAG} -X main.gitCommit=${TRAVIS_COMMIT} -X main.buildDate=$(date --iso-8601)" -o clickhouse-backup/clickhouse-backup && \
  # Creating default config
  ./clickhouse-backup/clickhouse-backup default-config > clickhouse-backup/config.yml && \
  # Running unit tests
  go test -v && \
  # Decrypting credentials for Google Cloud Storage
  openssl enc -base64 -aes-256-cbc -d -in integration-test/credentials.json.enc -out integration-test/credentials.json -k ${VAULT_PASSWORD} && \
  # Preparing to integration tests
  docker-compose -f integration-test/docker-compose-travis.yml up -d --force-recreate && \
  # Running integration tests
  go test -tags=integration && \
  # Building docker image
  docker build -t alexakulov/clickhouse-backup:master .
after_success:
  - tar -czvf clickhouse-backup.tar.gz clickhouse-backup
deploy:
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: clickhouse-backup.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh release
    on:
      tags: true
