clickhouse:
  username: default
  password: ""
  host: localhost
  port: 9000
  data_path: ""
s3:
  access_key: ""
  secret_key: ""
  bucket: ""
  endpoint: ""
  region: us-east-1
  acl: private
  force_path_style: false
  path: ""
  disable_ssl: false
  disable_progress_bar: false
  overwrite_strategy: always
  part_size: 5242880
  delete_extra_files: true
backup:
  strategy: tree
  backups_to_keep: 0
