version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get .
      - run: go build

workflows:
  version: 2
  build:
    jobs:
      - build
