version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    working_directory: /go/src/github.com/AlexAkulov/clickhouse-backup
    steps:
      - checkout
      - run: go get .
      - run: go build

workflows:
  version: 2
  build:
    jobs:
      - build
