version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - run: go get .
      - run: go build

workflows:
  version: 2
  build:
    jobs:
      - build
