version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go build -o clickhouse-backup/clickhouse-backup
      - run: ./clickhouse-backup/clickhouse-backup default-config > clickhouse-backup/config.yml
      - run: export VERSION=$(./clickhouse-backup/clickhouse-backup --version)
      - run: tar -czvf clickhouse-backup.tar.gz clickhouse-backup
      - persist_to_workspace:
          root: .
          paths:
            - clickhouse-backup.tar.gz

  publish-master:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: clickhouse-backup.tar.gz
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -prerelease -recreate master clickhouse-backup.tar.gz

  publish-release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: clickhouse-backup.tar.gz
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} clickhouse-backup.tar.gz

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-master:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-release:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
