version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go build -o clickhouse-backup/clickhouse-backup
      - run: ./clickhouse-backup/clickhouse-backup default-config > clickhouse-backup/config.yml
      - run: export VERSION=$(./clickhouse-backup/clickhouse-backup --version)
      - run: tar -czvf clickhouse-backup.tar.gz clickhouse-backup
      - persist_to_workspace:
          root: .
          paths:
            - clickhouse-backup
            - clickhouse-backup.tar.gz

  integration-test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: clickhouse-backup
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run: /usr/local/bin/docker-compose -f integration-test/docker-compose.yml up --detach
      - run: go test -tags integration

  publish-master:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: clickhouse-backup.tar.gz
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -prerelease -recreate latest clickhouse-backup.tar.gz

  publish-release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: clickhouse-backup.tar.gz
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} clickhouse-backup.tar.gz

workflows:
  version: 2
  main:
    jobs:
      - build
      - integration-test:
          requires:
            - build
      - publish-master:
          requires:
            - integration-test
          filters:
            branches:
              only: master
      - publish-release:
          requires:
            - integration-test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
