version: "3"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access
      MINIO_SECRET_KEY: secret
    command: server doc_gen_minio/export
    networks:
      - back-tier

  clickhouse:
    image: yandex/clickhouse-server:18.12.17
    container_name: clickhouse
    volumes:
      - ./:/app
    command: "/usr/bin/clickhouse-server --config=${CLICKHOUSE_CONFIG}"
    networks:
      - back-tier

  app:
    build: ./
    volumes:
      - ./:/app
    networks:
      - back-tier
    ports:
      - "3003:3003"
    stdin_open: true
    tty: true
    environment:
      AWS_ACCESS_KEY: "access"
      AWS_SECRET_KEY: "secret"
      AWS_HOST: "http://doc_gen_minio:9000"
      AWS_DISABLE_SSL: "true"
      AWS_S3_FORCE_PATH_STYLE: "true"
      AWS_BUCKET: "output"

volumes:
  db-data:

networks:
  back-tier:
