name: Build

on:
  release:
    types: [published, created, edited]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup golang
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'


#      - name: Cache golang
#        id: cache-golang
#        uses: actions/cache@v2
#        with:
#          path: /github/home/go/pkg/mod
#          key: ${{ runner.os }}-${{ matrix.golang-version }}-golang-${{ hashFiles('go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-${{ matrix.golang-version }}-golang-
#
#      - name: Install golang dependencies
#        run: go mod download -x
#        if: |
#          steps.cache-golang.outputs.cache-hit != 'true'

      - name: Setup fpm
        run: |
          apt-get install -y --no-install-recommends ruby ruby-dev gcc g++ rpm
          gem install --no-document fpm

      - name: Setup make
        run: |
          apt-get update
          apt-get install --no-install-recommends -y make

      - run: make build
      - run: make config
      - run: make test


      - name: Building deb, rpm and tar.gz packages
        run: |
          tar -czvf clickhouse-backup.tar.gz clickhouse-backup
          CGO_ENABLED=0 make packages


      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ${{ steps.changelog.outputs.path }}
          draft: true

      - name: Add plugin to release
        id: upload-plugin-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/${{ steps.metadata.outputs.archive }}
          asset_name: ${{ steps.metadata.outputs.archive }}
          asset_content_type: application/zip

      - name: Building docker image
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

          DOCKER_TAG: ${{ github.event.release.tag_name }}
        run: |
          echo ${DOCKER_BRANCH} ${DOCKER_TAG} ${DOCKER_REPO}
          echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USER} --password-stdin

          docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG:-dev} .
          docker image tag ${DOCKER_IMAGE}:${DOCKER_TAG:-dev} $DOCKER_REGISTRY/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG:-dev}
          docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG:-dev}

          echo "Successfull pushed ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}:${DOCKER_TAG:-dev}"



